---
#creation of ec2 instance and installing apache server and hosting web page 
- hosts: localhost
  connection: local

  tasks:
    - name: launching ec2 instance for webserver
      amazon.aws.ec2_instance:
        key_name: pem-key
        instance_type: t2.micro
        image_id: ami-008fe2fc65df48dac
        wait: true
        security_group: pub-sg
        count: 1
        vpc_subnet_id: subnet-0d0c29306714c19e1
        network:
          assign_public_ip: true
        region: us-west-2
        state: present
        tags:
          Name: webserver
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: webserver
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

- hosts: webserver
  gather_facts: no
  tasks:
  - name: running role
    include_role:
      name: httpdserver
